# Generated by Django 4.0.2 on 2023-02-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
